In [102]:
import rasterio
from rasterio.plot import show
fp = "datasets/DIM_SPOT7_PMS_202301220703517_ORT_AKWOI-00056166/PROD_SPOT7_001/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_202301220703517_ORT_AKWOI-00056166_R2C2.TIF"
img = rasterio.open(fp)
img.crs


CRS.from_epsg(4326)

In [103]:
img.count

4

In [104]:


newarr = img.read()//16

newarr.max()

255

In [105]:
newarr.shape

(4, 5405, 7353)

In [106]:
import numpy as np
import cv2
from PIL import Image

def split_image(img, window_size, overlap):
    height, width = img.shape[1:]
    img= np.swapaxes(img, 0, 2)
    img = Image.fromarray(img.astype(np.uint8))
    x_step = window_size - overlap
    y_step = window_size - overlap
    for y in range(0, height, y_step):
        for x in range(0, width, x_step):
            #image = img[y:y+window_size, x:x+window_size, :]
            box = (y,  x, y+window_size, x+window_size)
            print(box)
            img.crop(box).save(f"datasets/new_images/real_image_2023_22_{x}_{y}.jpg")
            #Image.fromarray(image.astype(np.uint8)).save(f"datasets/new_images/real_image_2020_12_{x}_{y}.jpg")
            


#47.91

window_size = 2048
overlap = 512
split_image(newarr[:3], window_size, overlap)

(0, 0, 2048, 2048)
(0, 1536, 2048, 3584)
(0, 3072, 2048, 5120)
(0, 4608, 2048, 6656)
(0, 6144, 2048, 8192)
(1536, 0, 3584, 2048)
(1536, 1536, 3584, 3584)
(1536, 3072, 3584, 5120)
(1536, 4608, 3584, 6656)
(1536, 6144, 3584, 8192)
(3072, 0, 5120, 2048)
(3072, 1536, 5120, 3584)
(3072, 3072, 5120, 5120)
(3072, 4608, 5120, 6656)
(3072, 6144, 5120, 8192)
(4608, 0, 6656, 2048)
(4608, 1536, 6656, 3584)
(4608, 3072, 6656, 5120)
(4608, 4608, 6656, 6656)
(4608, 6144, 6656, 8192)


In [4]:


from PIL import Image
import os
import random
import math

# Load image
img = Image.open("datasets/synthetic_images/no_label/empty_sea_23.jpg")

# Output directory for the smaller images
output_dir = 'datasets/synthetic_images/no_label/'

# Parameters for cropping
crop_size = 680
overlap = 120

# Calculate the number of crops in the x and y directions
num_crops_x = (img.width - crop_size) // (crop_size - overlap) + 1
num_crops_y = (img.height - crop_size) // (crop_size - overlap) + 1

# Loop over each crop
for i in range(num_crops_x):
    for j in range(num_crops_y):
        # Calculate the coordinates for cropping the image
        left = i * (crop_size - overlap)
        top = j * (crop_size - overlap)
        right = left + crop_size
        bottom = top + crop_size

        # Crop the image
        cropped_img = img.crop((left, top, right, bottom))

        # Save the cropped image with a random name
        image_name = os.path.join(output_dir, f'S_23_E_{i}_{j}.png')
        cropped_img.save(image_name)

In [19]:
import numpy as np 

label = np.ones([680, 680, 3], dtype=int)

img= Image.fromarray(label.astype(np.uint8))
output_dir = 'datasets/synthetic_images/total/'
for i in os.listdir(output_dir):
    image_name = output_dir + i.replace("S", "L")
    img.save(image_name)

In [27]:

from PIL import Image
import os
import random
import math

# Load image
img = Image.open("datasets/synthetic_images/platforms/empty_sea_pt_20.jpg")
lab_pt = Image.open("datasets/synthetic_images/task-60-annotation-101-by-2-tag-platform-0.png")

nppt = np.asarray(lab_pt)
print(nppt)
newpt= np.zeros_like([nppt, nppt, nppt])
newpt[1] = nppt
print(newpt)
newpt= np.swapaxes(newpt, 0, 1)
newpt= np.swapaxes(newpt, 1, 2)


lab_pt = Image.fromarray(newpt.astype(np.uint8))


# Output directory for the smaller images
output_dir = 'datasets/synthetic_images/total/'

# Parameters for cropping
crop_size = 680
overlap = 400

# Calculate the number of crops in the x and y directions
num_crops_x = (img.width - crop_size) // (crop_size - overlap) + 1
num_crops_y = (img.height - crop_size) // (crop_size - overlap) + 1

# Loop over each crop
for i in range(num_crops_x):
    for j in range(num_crops_y):
        # Calculate the coordinates for cropping the image
        left = i * (crop_size - overlap)
        top = j * (crop_size - overlap)
        right = left + crop_size
        bottom = top + crop_size

        # Crop the image
        cropped_img = img.crop((left, top, right, bottom))
        cropped_lab = lab_pt.crop((left, top, right, bottom))

        # Save the cropped image with a random name
        image_name = os.path.join(output_dir, f'S_20_PT_{i}_{j}.png')
        lab_name = os.path.join(output_dir, f'N_20_PT_{i}_{j}.png')
        cropped_img.save(image_name)
        cropped_lab.save(lab_name)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [38]:
from PIL import Image
import os
import random
import math

# Load image
img = Image.open("datasets/synthetic_images/oil_platforms/empty_sea_pt_woil_20.jpg")
lab_pt = Image.open("datasets/synthetic_images/task-60-annotation-101-by-2-tag-platform-0.png")
lab_leak = Image.open("datasets/synthetic_images/task-60-annotation-101-by-2-tag-leak-0.png")


nppt = np.asarray(lab_pt)
npleak = np.asarray(lab_leak)
newpt= np.zeros_like([nppt, nppt, nppt])

newpt[1] = nppt
newpt[2] = npleak

newpt= np.swapaxes(newpt, 0, 1)
newpt= np.swapaxes(newpt, 1, 2)


lab_pt = Image.fromarray(newpt.astype(np.uint8))


# Output directory for the smaller images
output_dir = 'datasets/synthetic_images/total/'

# Parameters for cropping
crop_size = 680
overlap = 340

# Calculate the number of crops in the x and y directions
num_crops_x = (img.width - crop_size) // (crop_size - overlap) + 1
num_crops_y = (img.height - crop_size) // (crop_size - overlap) + 1

# Loop over each crop
for i in range(num_crops_x):
    for j in range(num_crops_y):
        # Calculate the coordinates for cropping the image
        left = i * (crop_size - overlap)
        top = j * (crop_size - overlap)
        right = left + crop_size
        bottom = top + crop_size

        # Crop the image
        cropped_img = img.crop((left, top, right, bottom))
        cropped_lab = lab_pt.crop((left, top, right, bottom))

        # Save the cropped image with a random name
        image_name = os.path.join(output_dir, f'S_20_WLPT_{i}_{j}.png')
        lab_name = os.path.join(output_dir, f'L_20_WLPT_{i}_{j}.png')
        cropped_img.save(image_name)
        cropped_lab.save(lab_name)

In [1]:
synthetic_images_path = "datasets/real_images/"
synthetic_csv_path = "datasets/real_images/label_txt.txt"


import os



with open(synthetic_csv_path, 'w') as f:
    for i in os.listdir(synthetic_images_path):
        f.write(f"{i}\n")




